### ISSUE TITLE
Installation of pattern3 module

### ISSUE THREAD

**Issue by hansen7** [brianhie/mutational-semantics-neurips2020#1]
Hi, @brianhie. Thanks for providing this code! 

It seems that `pattern3` is no longer in maintenance on PyPI, are you following the instructions [here](https://github.com/clips/pattern/issues/217#issuecomment-370997258)?

**Comment by brianhie** [comment]
Hi @hansen7, I believe so, or I may have just cloned the GitHub repo and done `python setup.py install` as described here: https://github.com/clips/pattern#installation

**Comment by hansen7** [comment]
Thanks! I've just tried using `pip install pattern` on your provided link, and change `pattern3` to `pattern`, and it works!

**Comment by hansen7** [comment]
BTW, do you consider using something like [tf.distribute.Strategy](https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy) to make data-parallel computing? 
Just to make the training executable on GPU with smaller memories. 
For inference/test procedures, I can decrease the batch size and it won't bring noticeable differences, but I think a smaller batch size might hurt the training?

**Comment by brianhie** [comment]
We didn't split over GPUs but you could definitely try to add that functionality!

**Comment by hansen7** [comment]
Thanks! Will make a PR on this today/tmr!

**Comment by hansen7** [comment]
BTW, in configs such as `data/evcouplings/flu_h1_config.yaml`, there are some file paths that need changing, such as: `sequence_file: data/evcouplings/flu_h1_seq.fa`。。。
