### ISSUE TITLE
Unsolved reference of lstm and bilstm

### ISSUE THREAD

**Issue by hansen7** [brianhie/mutational-semantics-neurips2020#2]
Hi @brianhie. Thanks for providing the code!

I found no reference of `lstm` and `bilstm` called here:
https://github.com/brianhie/mutational-semantics-neurips2020/blob/60fa9ee3689802dcf41ba05fad79647bab6ddbe8/bin/headlines.py#L141-L147

Would you mind clarifying this?

**Comment by brianhie** [comment]
The models themselves are loaded from https://github.com/brianhie/mutational-semantics-neurips2020/blob/60fa9ee3689802dcf41ba05fad79647bab6ddbe8/bin/mutation.py#L6. Does that answer your question?

**Comment by hansen7** [comment]
Thanks, get it !
