### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by willow-yll** [brianhie/mutational-semantics-neurips2020#4]
Hello，I am very interested in escape dataset，and I have some question：   
How to set a threshold to judge which mutation is immune escape？ 
What is the meaning of mutdiffsel、abs_diffsel....... in the data?  
Or, which column should I focus on?  
Could you please make an explanatory document for the data？    
![image](https://user-images.githubusercontent.com/79819922/133871797-177a8bf3-67dc-47c6-a8ec-e9e2a5fcc398.png)
![image](https://user-images.githubusercontent.com/79819922/133871815-5bbce0ea-1942-4e09-8268-b69a6c76dccd.png)

**Comment by brianhie** [comment]
Hi @willow-yll, please take a look here to see how the files get parsed as escapes: https://github.com/brianhie/mutational-semantics-neurips2020/blob/master/bin/escape.py
